#include "projects/newloop/main.cpp"
//#include "projects/nfeatures/main.cpp"
//#include "projects/specialchars/main.cpp"
//#include "projects/oldSys-stress/main.cpp"
//#include "projects/example/main.cpp"
//#include "projects/pacman/pacman.cpp"
//#include "projects/snake/snake.cpp"
//#include "projects/tictactoe/main.cpp"
